"""initial schema: rol, usuario, curriculo, ods, situacion, version

Revision ID: a166a5664bf1
Revises: 
Create Date: 2026-05-09 17:39:55.160854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a166a5664bf1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competencia',
    sa.Column('id_competencia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('materia', sa.String(length=50), nullable=True),
    sa.Column('curso', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id_competencia')
    )
    with op.batch_alter_table('competencia', schema=None) as batch_op:
        batch_op.create_index('ix_competencia_materia_curso', ['materia', 'curso'], unique=False)

    op.create_table('ods',
    sa.Column('id_ods', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id_ods'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('permisos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('saber_basico',
    sa.Column('id_saber', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bloque', sa.String(length=100), nullable=False),
    sa.Column('materia', sa.String(length=50), nullable=False),
    sa.Column('curso', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id_saber')
    )
    with op.batch_alter_table('saber_basico', schema=None) as batch_op:
        batch_op.create_index('ix_saber_materia_curso', ['materia', 'curso'], unique=False)

    op.create_table('criterio_evaluacion',
    sa.Column('id_criterio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('id_competencia', sa.Integer(), nullable=False),
    sa.Column('curso', sa.String(length=20), nullable=False),
    sa.Column('materia', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_competencia'], ['competencia.id_competencia'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_criterio')
    )
    with op.batch_alter_table('criterio_evaluacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_criterio_evaluacion_id_competencia'), ['id_competencia'], unique=False)
        batch_op.create_index('ix_criterio_materia_curso', ['materia', 'curso'], unique=False)

    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('centro_educativo', sa.String(length=200), nullable=True),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.Column('comunidad_autonoma', sa.String(length=50), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultima_sesion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_correo'), ['correo'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuario_id_rol'), ['id_rol'], unique=False)

    op.create_table('situacion_aprendizaje',
    sa.Column('id_situacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('comunidad_autonoma', sa.String(length=50), nullable=True),
    sa.Column('curso', sa.String(length=20), nullable=False),
    sa.Column('materia', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('metodologia', sa.String(length=100), nullable=True),
    sa.Column('num_sesiones', sa.Integer(), nullable=True),
    sa.Column('duracion_sesion_minutos', sa.Integer(), nullable=True),
    sa.Column('idioma', sa.String(length=10), nullable=False),
    sa.Column('perfil_aula', sa.Text(), nullable=True),
    sa.Column('materiales_contexto', sa.Text(), nullable=True),
    sa.Column('contenido', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id_situacion_origen', sa.Integer(), nullable=True),
    sa.Column('tipo_adaptacion', sa.String(length=30), nullable=True),
    sa.Column('perfil_alumnado', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_situacion_origen'], ['situacion_aprendizaje.id_situacion'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_situacion')
    )
    with op.batch_alter_table('situacion_aprendizaje', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_situacion_aprendizaje_curso'), ['curso'], unique=False)
        batch_op.create_index(batch_op.f('ix_situacion_aprendizaje_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_situacion_aprendizaje_id_situacion_origen'), ['id_situacion_origen'], unique=False)
        batch_op.create_index(batch_op.f('ix_situacion_aprendizaje_id_usuario'), ['id_usuario'], unique=False)
        batch_op.create_index(batch_op.f('ix_situacion_aprendizaje_materia'), ['materia'], unique=False)

    op.create_table('situacion_competencia',
    sa.Column('id_situacion', sa.Integer(), nullable=False),
    sa.Column('id_competencia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_competencia'], ['competencia.id_competencia'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_situacion'], ['situacion_aprendizaje.id_situacion'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_situacion', 'id_competencia')
    )
    op.create_table('situacion_criterio',
    sa.Column('id_situacion', sa.Integer(), nullable=False),
    sa.Column('id_criterio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_criterio'], ['criterio_evaluacion.id_criterio'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_situacion'], ['situacion_aprendizaje.id_situacion'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_situacion', 'id_criterio')
    )
    op.create_table('situacion_ods',
    sa.Column('id_situacion', sa.Integer(), nullable=False),
    sa.Column('id_ods', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ods'], ['ods.id_ods'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_situacion'], ['situacion_aprendizaje.id_situacion'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_situacion', 'id_ods')
    )
    op.create_table('situacion_saber',
    sa.Column('id_situacion', sa.Integer(), nullable=False),
    sa.Column('id_saber', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_saber'], ['saber_basico.id_saber'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_situacion'], ['situacion_aprendizaje.id_situacion'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_situacion', 'id_saber')
    )
    op.create_table('version',
    sa.Column('id_version', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_situacion', sa.Integer(), nullable=False),
    sa.Column('numero_version', sa.Integer(), nullable=False),
    sa.Column('contenido', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('descripcion_cambio', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_situacion'], ['situacion_aprendizaje.id_situacion'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_version')
    )
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_version_id_situacion'), ['id_situacion'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_version_id_situacion'))

    op.drop_table('version')
    op.drop_table('situacion_saber')
    op.drop_table('situacion_ods')
    op.drop_table('situacion_criterio')
    op.drop_table('situacion_competencia')
    with op.batch_alter_table('situacion_aprendizaje', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_situacion_aprendizaje_materia'))
        batch_op.drop_index(batch_op.f('ix_situacion_aprendizaje_id_usuario'))
        batch_op.drop_index(batch_op.f('ix_situacion_aprendizaje_id_situacion_origen'))
        batch_op.drop_index(batch_op.f('ix_situacion_aprendizaje_estado'))
        batch_op.drop_index(batch_op.f('ix_situacion_aprendizaje_curso'))

    op.drop_table('situacion_aprendizaje')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_id_rol'))
        batch_op.drop_index(batch_op.f('ix_usuario_correo'))

    op.drop_table('usuario')
    with op.batch_alter_table('criterio_evaluacion', schema=None) as batch_op:
        batch_op.drop_index('ix_criterio_materia_curso')
        batch_op.drop_index(batch_op.f('ix_criterio_evaluacion_id_competencia'))

    op.drop_table('criterio_evaluacion')
    with op.batch_alter_table('saber_basico', schema=None) as batch_op:
        batch_op.drop_index('ix_saber_materia_curso')

    op.drop_table('saber_basico')
    op.drop_table('rol')
    op.drop_table('ods')
    with op.batch_alter_table('competencia', schema=None) as batch_op:
        batch_op.drop_index('ix_competencia_materia_curso')

    op.drop_table('competencia')
    # ### end Alembic commands ###
